# Generated by Django 4.2.16 on 2024-10-12 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_id', models.AutoField(primary_key=True, serialize=False)),
                ('aircraft_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_produced', models.BooleanField(default=False)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aircraft')),
                ('used_avionics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avionics', to='api.part')),
                ('used_fuselage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuselage', to='api.part')),
                ('used_tail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tail', to='api.part')),
                ('used_wing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wing', to='api.part')),
            ],
        ),
    ]
