# Generated by Django 4.2.16 on 2024-10-12 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='part',
            name='is_used',
        ),
        migrations.CreateModel(
            name='ProducedPart',
            fields=[
                ('produced_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_used', models.BooleanField(default=False)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aircraft')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.part')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='production',
            name='used_avionics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avionics', to='api.producedpart'),
        ),
        migrations.AlterField(
            model_name='production',
            name='used_fuselage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuselage', to='api.producedpart'),
        ),
        migrations.AlterField(
            model_name='production',
            name='used_tail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tail', to='api.producedpart'),
        ),
        migrations.AlterField(
            model_name='production',
            name='used_wing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wing', to='api.producedpart'),
        ),
    ]
