# Generated by Django 4.2.16 on 2024-10-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_producedpart_producer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producedpart',
            name='produced_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='production',
            name='produced_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
